# Run on a schedule
trigger: none
pr: none

schedules:
  - cron: '0 9 * * Mon-Thu'
    displayName: Nightly Release Schedule
    always: true
    branches:
      include:
        - main

jobs:
  - job: nightly_release
    displayName: Nightly Release
    pool:
      name: Hosted macOS
    steps:
      - template: scripts/ci/common-setup.yml

      - task: ComponentGovernanceComponentDetection@0
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'High'

      - script: yarn run test
        displayName: Run test suite
        env:
          TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml

      - script: yarn global add vsce
        displayName: Install vsce

      - script: >
          node ./scripts/prepare-nightly-build.js
          -v "$VERSION" -i "$NAME" -n "$DISPLAYNAME" -d "$DESCRIPTION" -p "$PUBLISHER"
        displayName: Generate package.json
        env:
          NAME: vscode-pull-request-github-insiders
          DISPLAYNAME: GitHub Pull Request Nightly Build
          DESCRIPTION: Nightly Build GitHub Pull Request extension
          PUBLISHER: GitHub
